stages:
  prepare:
    cmd: python src/prepare.py
    deps:
      - data/raw/${prepare.dataset}
      - src/prepare.py
      - src/config.py
    params:
      - prepare
    outs:
      - data/split/${prepare.dataset}

  train:
    cmd: python src/train.py
    deps:
      - data/split/${prepare.dataset}
      - src/train.py
      - src/config.py
    params:
      - train

  evaluate:
    cmd: python src/evaluate/evaluate_orientation.py
    deps:
      - data/split/${prepare.dataset}
      - src/evaluate/evaluate_orientation.py
    params:
      - evaluate
      - prepare.dataset
    outs:
      - ${evaluate.output_dir}/${prepare.dataset}:
          cache: false
