"""
Генерація CML звіту для Pull Request.

Використання:
    python scripts/generate_report.py > report.md

Створює markdown-звіт з:
  - Таблицею метрик
  - Посиланням на confusion_matrix (через cml publish)
  - Результатом Quality Gate
  - Порівнянням з baseline (якщо є)
"""

import json
import os
import subprocess
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent


def publish_image(image_path: str) -> str:
    """Публікує зображення через cml publish і повертає markdown."""
    try:
        result = subprocess.run(
            ["cml", "publish", image_path, "--md"],
            capture_output=True, text=True, timeout=60,
        )
        if result.returncode == 0 and result.stdout.strip():
            return result.stdout.strip()
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass
    return f"*(зображення: {image_path})*"


def main():
    metrics_path = PROJECT_ROOT / "metrics.json"
    baseline_path = PROJECT_ROOT / "baseline" / "metrics.json"

    report = []
    report.append("## 🤖 Model CI Report")
    report.append("")

    # ── Метрики ────────────────────────────────────────────────────────────
    if metrics_path.exists():
        with open(metrics_path) as f:
            metrics = json.load(f)

        report.append("### 📊 Metrics")
        report.append("")
        report.append("| Metric | Value |")
        report.append("|--------|-------|")
        for k, v in sorted(metrics.items()):
            if k == "_raw":
                continue
            report.append(f"| {k} | {float(v):.4f} |")
        report.append("")

        # ── Baseline порівняння ────────────────────────────────────────────
        if baseline_path.exists():
            with open(baseline_path) as f:
                baseline = json.load(f)

            report.append("### 📈 Comparison vs. Baseline")
            report.append("")
            report.append("| Metric | Baseline | Current | Δ |")
            report.append("|--------|----------|---------|---|")

            all_keys = sorted(
                set(list(baseline.keys()) + list(metrics.keys())) - {"_raw"}
            )
            for key in all_keys:
                b = baseline.get(key)
                c = metrics.get(key)
                if b is not None and c is not None:
                    delta = float(c) - float(b)
                    sign = "+" if delta > 0 else ""
                    emoji = "🟢" if delta >= 0 else "🔴"
                    report.append(
                        f"| {key} | {float(b):.4f} | {float(c):.4f} | {emoji} {sign}{delta:.4f} |"
                    )
                elif c is not None:
                    report.append(f"| {key} | — | {float(c):.4f} | 🆕 |")
            report.append("")

        # ── Quality Gate ───────────────────────────────────────────────────
        map50_threshold = float(os.getenv("MAP50_THRESHOLD", "0.01"))
        map50 = metrics.get("mAP50")

        report.append("### 🚦 Quality Gate")
        report.append("")
        if map50 is not None:
            passed = float(map50) >= map50_threshold
            status = "✅ PASSED" if passed else "❌ FAILED"
            report.append(
                f"- mAP50: **{float(map50):.4f}** (threshold: {map50_threshold:.4f}) → {status}"
            )
        else:
            report.append("- mAP50: *не доступна*")
        report.append("")

    else:
        report.append("⚠️ `metrics.json` не знайдено — тренування не виконувалось.")
        report.append("")

    # ── Візуалізації ───────────────────────────────────────────────────────
    cm_path = PROJECT_ROOT / "confusion_matrix.png"
    if cm_path.exists():
        report.append("### 📸 Confusion Matrix")
        report.append("")
        report.append(publish_image(str(cm_path)))
        report.append("")

    cm_norm_path = PROJECT_ROOT / "confusion_matrix_normalized.png"
    if cm_norm_path.exists():
        report.append("### 📸 Confusion Matrix (Normalized)")
        report.append("")
        report.append(publish_image(str(cm_norm_path)))
        report.append("")

    # ── Результат ──────────────────────────────────────────────────────────
    report.append("---")
    report.append("*Generated by CI pipeline*")

    print("\n".join(report))


if __name__ == "__main__":
    main()
